version: "3.7"

services:
  flask-test:
    build:
      context: ./
      dockerfile: ./dockerfiles/flask/Dockerfile
    command: >
      bash -c "set -x;
               cd /opt/services/flaskapp/api;
               pip install -r ./requirements.txt;
               sleep infinity;"
    container_name: ${COMMAND_NAME}-flask
    environment:
      - ENV=${ENV:-development}
      - POSTGRES_URL=postgresql://${DB_NAME}_user:${DB_NAME}_password@postgres/${DB_NAME}
    networks:
      - db_nw
      - web_nw
    depends_on:
      - postgres-test
    volumes:
      - ./:/opt/services/flaskapp

  postgres-test:
    image: postgres:10.1
    container_name: ${COMMAND_NAME}-postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_NAME}_user
      - POSTGRES_PASSWORD=${DB_NAME}_password
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_min_duration_statement=0 -c log_statement=all -c log_duration=on
    networks:
      - db_nw
    ports:
      - 5433:5432
    volumes:
      - postgres_data_test:/var/lib/postgresql-test/data

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge

volumes:
  postgres_data_test:
