version: "3.7"

services:
  apiweb:
    build: .
    command: >
      bash -c "set -x;
               cd /opt/apiweb;
               pip install -r ./requirements.txt;
               sleep infinity;"
    container_name: ${APP_NAME}-apiweb
    depends_on:
      - apidb
    env_file:
      - ./.env
    environment:
      - GITHUB_NAME=${GITHUB_NAME}
      - MODULE_NAME=${MODULE_NAME}
      - ENV=${ENV:-development}
      - PIP_NAME=${PIP_NAME}
      - POSTGRES_URL=postgresql://${APP_NAME}_user:${APP_NAME}_password@apidb/${APP_NAME}_api
    networks:
      - db_nw
      - web_nw
    volumes:
      - ./:/opt/apiweb

  apidb:
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_min_duration_statement=0 -c log_statement=all -c log_duration=on
    container_name: ${APP_NAME}-apidb
    environment:
      - POSTGRES_DB=${APP_NAME}_api
      - POSTGRES_PASSWORD=${APP_NAME}_password
      - POSTGRES_USER=${APP_NAME}_user
    image: postgres:12.2
    networks:
      - db_nw
    volumes:
      - ./docker_data/apidb:/var/lib/postgresql

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge

volumes:
  docker_data:
